name: build-and-release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        include:
          - os: windows-latest
            output_name: terminara.exe
          - os: ubuntu-latest
            output_name: terminara

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -e .
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller terminara.spec

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.output_name }}
          token: ${{ secrets.GITHUB_TOKEN }}